apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: playlist-service
  name: playlist-service
  namespace: mid
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 31001
  selector:
    app: playlist-service
  type: NodePort
status:
  loadBalancer: {}
